### ISSUE TITLE
It is a WordPress theme

### ISSUE THREAD

**Issue by szepeviktor** [BracketSpace/WP-Admin-Reference#3]
Hello!
Please consider putting the theme only in this repo, the project in another.
After [registering it on packagist](https://packagist.org/packages/bracketspace/wpadminreference) it will be very easy to install :) 1 composer command

**Comment by Kubitomakita** [comment]
Hey, this theme is not intended to use like this, but if you are interested in something installable, take a look at: https://github.com/bueltge/wordpress-admin-style

**Comment by szepeviktor** [comment]
All right.
Thank you.
